name: Deploy to ECS

on:
  push:
    branches: [main]

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Pull code
        uses: actions/checkout@v2

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          export DOCKER_BUILDKIT=1
          docker build --build-arg BUILDKIT_INLINE_CACHE=1 --cache-from "${ECR_REGISTRY}/barberriley" -t $ECR_REGISTRY/barberriley:$IMAGE_TAG -t $ECR_REGISTRY/barberriley:latest .
          docker push $ECR_REGISTRY/barberriley:$IMAGE_TAG

      - name: Update ECS Task Definition
        id: create-task-definition
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: ecs-task-definition.json
          container-name: barberriley-frontend
          image: 264936567933.dkr.ecr.eu-west-2.amazonaws.com/barberrile:${{ github.sha }}

      - name: Deploy new Task Definition to Amazon ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.create-task-definition.outputs.task-definition }}
          service: barberriley-service
          cluster: barberriley

      - name: Update Service and Force New Deployment
        run: aws ecs update-service --cluster barberriley --service barberriley-service --force-new-deployment --region eu-west-2
